# Generated by Django 4.2.4 on 2023-08-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=10)),
                ('kcal', models.CharField(max_length=10)),
                ('carbon', models.CharField(max_length=10)),
                ('pro', models.CharField(max_length=10)),
                ('fat', models.CharField(max_length=10)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('total', models.CharField(blank=True, max_length=10, null=True)),
                ('kcal', models.CharField(blank=True, max_length=10, null=True)),
                ('carbon', models.CharField(blank=True, max_length=10, null=True)),
                ('pro', models.CharField(blank=True, max_length=10, null=True)),
                ('fat', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
