# Generated by Django 4.2.4 on 2023-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_food_carbon_alter_food_fat_alter_food_kcal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='carbon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='kcal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
